name: Practice Challenge Workflow
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Nodejs
              uses: actions/setup-node@v5
            - name: Print Node and NPM version
              run: |
                  node -v
                  npm -v
            - name: Install Dependencies
              run: npm ci
            - name: Perform Linting
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v5
            - name: Print Node and NPM versions
              run: |
                  node -v
                  npm -v
            - name: Install Dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v5
            - name: Print Node and NPM Versions
              run: |
                  node -v
                  npm -v
            - name: Install dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy the codebase
              run: echo "Deploying the code ..."
